# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: docker build -t katalonstudio/katalon .
  displayName: 'Pull katalon studio images'
- script: docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey="d6b5da09-9b5f-44da-a359-69a35be47228" --config -webui.autoUpdateDrivers=true -sendMail='nguyennngoctolinh@gmail.com'
  displayName: 'Runnning Katalon TS_RegressionTest'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/
