# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: docker build -t katalonstudio/katalo .
  displayName: 'Pull dockerfile'
- script: docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -browserType="Chrome (headless)" -retry=0 -statusDelay=15 -testSuiteCollectionPath="Test Suites/TS_RegressionTestCollection" -apiKey="1a76271f-d2c0-4079-b892-98e59860ebcf" -sendMail="nguyennngoctolinh@gmail.com" --config -webui.autoUpdateDrivers=true
  displayName: 'Runnning Katalon TS_RegressionTestCollection'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/
    
    
trigger:
  batch: true
  branches:
    include:
      - master

pr:
  - master

stages:
  - stage: Test
    jobs:
      - job: Test
        pool:
          vmImage: 'ubuntu-latest'

        steps:

          - checkout: self
            fetchDepth: 1
            clean: true

          - bash: |
              npm install
              npm test
            displayName: Test
          - task: DockerInstaller@0
            displayName: Docker Installer
            inputs:
              dockerVersion: 18.09.9
              releaseType: stable

          - bash: |
              set -ex
              export REPORT_PATH=$(pwd)/report
              docker run -t --rm -v \
                $REPORT_PATH:/Users/linhntnguyen/Desktop/Reports \
                -e PASSWORD=2658c724-2d3e-4f92-9dbe-f2645610d697  \
                -e PROJECT_ID=63553 \
                -e TYPE=katalon \
                -e REPORT_PATH=/Users/linhntnguyen/Desktop/Reports \
                katalonstudio/report-uploader:0.0.8
            displayName: Upload report to Katalon TestOps
            env:
              KATALON_API_KEY: 2658c724-2d3e-4f92-9dbe-f2645610d697
