# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: docker build -t Dockerfile .
  displayName: 'Pull dockerfile'
- script: docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -browserType="Chrome (headless)" -retry=0 -statusDelay=15 -testSuiteCollectionPath="Test Suites/TS_RegressionTestCollection" -apiKey="1a76271f-d2c0-4079-b892-98e59860ebcf" -sendMail="nguyennngoctolinh@gmail.com" --config -webui.autoUpdateDrivers=true
  displayName: 'Runnning Katalon TS_RegressionTestCollection'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/
